// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OtoparkTakipSistemi.DataAccess;

#nullable disable

namespace OtoparkTakipSistemi.DataAccess.Migrations
{
    [DbContext(typeof(OtoparkDbContext))]
    [Migration("20260617000000_AddSlotCapacity")]
    partial class AddSlotCapacity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("OtoparkTakipSistemi.Core.ParkingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParkingSlotId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParkingSlotId");

                    b.ToTable("ParkingRecords");
                });

            modelBuilder.Entity("OtoparkTakipSistemi.Core.ParkingSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Floor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("OccupiedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlotNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ParkingSlots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 3,
                            Floor = "Kat 1",
                            OccupiedCount = 0,
                            SlotNumber = "A-1"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2,
                            Floor = "Kat 1",
                            OccupiedCount = 0,
                            SlotNumber = "A-2"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 1,
                            Floor = "Kat 2",
                            OccupiedCount = 0,
                            SlotNumber = "B-1"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 1,
                            Floor = "Kat 2",
                            OccupiedCount = 0,
                            SlotNumber = "B-2"
                        });
                });

            modelBuilder.Entity("OtoparkTakipSistemi.Core.Tariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("TariffName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tariffs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 40.00m,
                            HourlyPrice = 15.00m,
                            TariffName = "Standart Gündüz Tarifesi"
                        });
                });

            modelBuilder.Entity("OtoparkTakipSistemi.Core.ParkingRecord", b =>
                {
                    b.HasOne("OtoparkTakipSistemi.Core.ParkingSlot", "ParkingSlot")
                        .WithMany()
                        .HasForeignKey("ParkingSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParkingSlot");
                });
#pragma warning restore 612, 618
        }
    }
}
